server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh_get           #路由id，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001      #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**            #断言，路径相匹配的进行路由
        - id: payment_routh_lb            #路由id，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001      #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**            #断言，路径相匹配的进行路由
            #- After=2020-11-01T14:47:09.829+08:00[Asia/Shanghai] # 在这个时间之后
            #- Before=2020-12-01T14:47:09.829+08:00[Asia/Shanghai] # 在这个时间之前
            #- Between=2020-11-01T14:47:09.829+08:00[Asia/Shanghai],2020-12-01T14:47:09.829+08:00[Asia/Shanghai] # 在这个时间之间
            #- Cookie=username,onlystatic #请求中要有username=onlystatic的cookie
            - Header=X-Request-Id,\d+ #请求头要有X-Request-Id属性且值为正整数的正则表达式
            #- Host=**.noonhope.com #请求主机必须为xxx.noonhope.com
            - Method=GET  #请求方式必须为GET
            - Query=username,\d+ #查询条件中必须有username且值为正整数的参数的正则表达式
            #curl http://localhost:9527/payment/lb?username=123 --cookie "username=onlystatic" -H "X-Request-id:123"

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://127.0.0.1:7001/eureka