server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:onlystatic/springcloud_config.git #Github上面的仓库名字
          #搜索目录
          search-paths:
            - springcloud_config
      #默认分支
      label: master

#注册服务到eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka

