server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #配置需要绑定RabbitMQ的服务信息
        defaultRabbit:  #表示定义的名称，用于和binding整合
          type: rabbit  #消息组件类型
          enviroment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input: #这个名字是一个通道的名字
          destination: studyExchange  #表示要用到的Exchange名称定义
          content-type: application/json #消息格式，文本text/plain
          binder: defaultRabbit #设置要绑定的消息服务具体设置
          group: noonhopeA #消费分组，多个服务同一个组就不会导致重复消费
#服务注册至eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳的间隔时间，默认30s
    lease-expiration-duration-in-seconds: 5 #如果超过5s收不到心跳就移除服务，默认90s
    instance-id: receive-8802.com  #在信息列表显示主机名称
    prefer-ip-address: true #访问的路径变为ip地址
